### ISSUE TITLE
API Callback

### ISSUE THREAD

**Issue by someone2875** [NekoWorld-r/NekoWorld-Tracker#2]
NekoWorld team

**Comment by Hikapu** [comment]
Вех автоматически создан в API Callback, пожалуйста, держите нас в курсе событий вашего кода.

 Создание API - одобрено.
 Построение конфигураций запущено.

**Comment by Hikapu** [comment]
Примечание: Пожалуйста, оформляйте свой код грамотно, дабы потом не возникло лишних вопросов.

**Comment by Hikapu** [comment]
—>
